export default {
  en: {
    10: 'UnLock Wallet',
    20: 'My Wallet',
    30: 'My Account',
    40: 'VNLA Balance',
    50: 'View on Etherscan',
    60: 'Sign Out',
    70: 'Cancel',
    80: 'Install Wallet',
    90: "'You'll need to install'",
    100: 'to continue. Once you have it installed, go ahead and',
    110: 'refresh the page',
    120: 'Install MetaMask',
  },
  zh: {
    10: '连接钱包',
    20: '我的钱包',
    30: '我的账户',
    40: 'VNLA Balance',
    50: '在Etherscan查看',
    60: '退 出',
    70: '取 消',
    80: '安装钱包',
    90: "您需要安装",
    100: '。安装成功后，',
    110: '请刷新页面',
    120: '前往安装',
  },
}
